- next.config.js
- package-lock.json
- package.json
- src/app/globals.css
- src/app/page.js
- src/components/Article/Article.js
- src/components/Button/ButtonWithBgColor.js
- src/components/Button/ButtonWithoutBgColor.js
- src/components/Card/Card.js
created button, article and card component
> card article button

- src/components/shared/Navbar.js
- src/components/shared/Theme.js
theme component bug was fixed and also browser error fixed
> Theme bug fixed

- src/app/page.js
- src/components/Banner/Banner.js
- src/components/shared/Navbar.js
update the Banner button, update the article margin and button, update home route in the logo
> [bugFixed](homepage bug fixed)

- FrontEnd/src/components/TextEditor/TextEditor.js
> [tempBugFixed](temporary bug fixed)

- FrontEnd/src/app/dashboard/write/page.js
- FrontEnd/src/components/TextEditor/TextEditor.js
successfully draft functionality implement & image upload by url
> Draft/text editor/joydip

- FrontEnd/src/app/dashboard/preference/page.js
- FrontEnd/src/app/globals.css
- FrontEnd/src/components/Preference/Preference.js
- FrontEnd/src/components/TextEditor/TextEditor.js
[added category and tags](update editor with next button with condition)
> [added category and tags](update editor with next button with condition)

- FrontEnd/src/components/Preference/Preference.js
- FrontEnd/src/components/TextEditor/TextEditor.js
remove editor border, redirect write page after submit the article & change button value
> Editor/category tags/joydip

- FrontEnd/src/app/dashboard/articles/[articleDetails]/page.js
- FrontEnd/src/app/dashboard/articles/page.js
dashboard article details page work
> Dashboard/artical details/joydip

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
- FrontEnd/src/app/dashboard/articleEdit/preference/page.js
- FrontEnd/src/app/dashboard/articles/[details]/page.js
- FrontEnd/src/app/dashboard/articles/page.js
- FrontEnd/src/components/TextEditor/TextEditor.js
update write page design & post successfully
> update write page design

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
- FrontEnd/src/components/TextEditor/TextEditor.js
> Write page/update/joydip

- FrontEnd/src/app/dashboard/articles/[details]/page.js
- FrontEnd/src/components/editor/Editor.js
Successfully build the website after update write page and update article details page in dashboard
> design update in the article dashboard details page

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
- FrontEnd/src/app/dashboard/articles/[details]/page.js
- FrontEnd/src/components/editor/Editor.js
> Article edit/joydip

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
update edit page and build done
> update edit page and build done

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
- FrontEnd/src/app/dashboard/articles/[details]/page.js
- FrontEnd/src/app/globals.css
- FrontEnd/src/components/newWrite/NewWrite.js
design update of dashboard article single page
> Dashboard/article/single page/joydip

- FrontEnd/src/app/layout.js
- FrontEnd/src/app/page.js
- FrontEnd/src/components/Banner/Banner.js
- FrontEnd/src/components/Contact/Contact.js
- FrontEnd/src/components/Popular/Popular.js
- FrontEnd/src/components/Trending/Trending.js
- FrontEnd/src/components/shared/Footer.js
> Home page/joydip

- FrontEnd/src/app/page.js
- FrontEnd/src/components/Banner/Banner.js
- FrontEnd/src/components/SubHeader/SubHeader.js
- FrontEnd/src/components/shared/Navbar.js
- FrontEnd/src/components/shared/Search/Search.js
added new sub headeing for reuse and respondive setup
> update navbar with responsive

- FrontEnd/src/app/article/[articleId]/page.js
- FrontEnd/src/app/article/page.js
- FrontEnd/src/app/globals.css
- FrontEnd/src/app/page.js
- FrontEnd/src/components/Banner/Banner.js
update the all article page and details page design
> update all articles page and details page

- FrontEnd/src/app/about/page.js
- FrontEnd/src/app/article/[articleId]/page.js
- FrontEnd/src/app/article/page.js
- FrontEnd/src/app/packages/page.js
- FrontEnd/src/app/page.js
- FrontEnd/src/components/Banner/Banner.js
- FrontEnd/src/components/SubHeader/SubHeader.js
- FrontEnd/src/components/shared/Navbar.js
- FrontEnd/src/components/shared/Search/Search.js
> update responsive all pages

- FrontEnd/src/app/dashboard/DashNavbar/page.js
- FrontEnd/src/app/dashboard/layout.js
change dashboard layout and make responsive (small device left)
> update dashboard layout

- FrontEnd/src/app/dashboard/articles/page.js
- FrontEnd/src/app/login/page.js
- FrontEnd/src/app/not-found.js
- FrontEnd/src/app/page.js
- FrontEnd/src/app/signup/page.js
- FrontEnd/src/components/Banner/Banner.js
- FrontEnd/src/components/Popular/Popular.js
- FrontEnd/src/components/Recomendation/page.js
- FrontEnd/src/components/shared/Loader/Loader.js
- FrontEnd/src/components/shared/Navbar.js
change login,signup,error page and home page responsive
> change login,signup,error page and home page responsive

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
- FrontEnd/src/app/dashboard/articles/page.js
- FrontEnd/src/app/dashboard/layout.js
- FrontEnd/src/components/editor/Editor.js
write & edit part useEffect issue fixed
> fixed the editor use effect issue

- FrontEnd/src/app/dashboard/articleEdit/[edit]/page.js
- FrontEnd/src/app/dashboard/articles/page.js
- FrontEnd/src/app/dashboard/layout.js
- FrontEnd/src/components/editor/Editor.js
- FrontEnd/src/components/shared/DeleteButton/DeleteButton.js
update delete button for fetch data after delete
> Fixed/editor/for deploy/joydip
